I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 29, in script call
    call tutorial_bus # 튜토리얼 장면 시작
  File "game/script.rpy", line 29, in script call
    call tutorial_bus # 튜토리얼 장면 시작
ScriptError: could not find label 'tutorial_bus'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 29, in script call
    call tutorial_bus # 튜토리얼 장면 시작
  File "E:\GameDevRenpy\renpy-8.1.1-sdk\renpy\ast.py", line 1725, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 29, in script call
    call tutorial_bus # 튜토리얼 장면 시작
  File "E:\GameDevRenpy\renpy-8.1.1-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'tutorial_bus'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
YabbaKusoDemo_1 1.0
Mon Jun 19 15:49:33 2023
